name: Docker Build CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Login to GHCR
    - name: Log in to the GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file baseimage --tag ghcr.io/fsteltenkamp/frankenphp-docker:latest

    - name: Push the Docker image
      run: docker push ghcr.io/fsteltenkamp/frankenphp-docker:latest