name: Docker Build CI

env:
  PHP_VERSION: 8.3
  LATEST: true

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Login to GHCR
    - name: Log in to the GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Base Docker image
      run: |
        if [ "${{ env.LATEST }}" = "true" ]; then
          docker build . --file baseimage --tag ghcr.io/fsteltenkamp/frankenphp-docker:latest --tag ghcr.io/fsteltenkamp/frankenphp-docker:php${{ env.PHP_VERSION }}
        else
          docker build . --file baseimage --tag ghcr.io/fsteltenkamp/frankenphp-docker:php${{ env.PHP_VERSION }}
        fi

    - name: Push the Base Docker image
      run: docker push ghcr.io/fsteltenkamp/frankenphp-docker:php${{ env.PHP_VERSION }}
    
    - name: Build the Nodejs Docker image
      run: |
        if [ "${{ env.LATEST }}" = "true" ]; then
          docker build . --file with_nodejs --tag ghcr.io/fsteltenkamp/frankenphp-docker:latest-nodejs --tag ghcr.io/fsteltenkamp/frankenphp-docker:php${{ env.PHP_VERSION }}-nodejs
        else
          docker build . --file with_nodejs --tag ghcr.io/fsteltenkamp/frankenphp-docker:php${{ env.PHP_VERSION }}-nodejs
        fi
    
    - name: Push the Nodejs Docker image
      run: docker push ghcr.io/fsteltenkamp/frankenphp-docker:php${{ env.PHP_VERSION }}-nodejs