name: Docker Build CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-8_3-cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build the image
      run: docker build . --file 8.3/cli/Dockerfile --tag ghcr.io/fsteltenkamp/frankenphp-docker:php8.3
    - name: Push the image
      run: docker push ghcr.io/fsteltenkamp/frankenphp-docker:php8.3
  build-8_3-mssql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build the image
      run: docker build . --file 8.3/mssql/Dockerfile --tag ghcr.io/fsteltenkamp/frankenphp-docker:php8.3-mssql
    - name: Push the Nodejs Docker image
      run: docker push ghcr.io/fsteltenkamp/frankenphp-docker:php8.3-mssql
  build-8_3-mssql-mysqli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build the image
      run: docker build . --file 8.3/mssql-mysqli/Dockerfile --tag ghcr.io/fsteltenkamp/frankenphp-docker:php8.3-mssql-mysqli
    - name: Push the Nodejs Docker image
      run: docker push ghcr.io/fsteltenkamp/frankenphp-docker:php8.3-mssql-mysqli
  build-8_3-mysqli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build the image
      run: docker build . --file 8.3/mysqli/Dockerfile --tag ghcr.io/fsteltenkamp/frankenphp-docker:php8.3-mysqli
    - name: Push the image
      run: docker push ghcr.io/fsteltenkamp/frankenphp-docker:php8.3-mysqli